spring:
  application:
    name: movement
    
  r2dbc:
    url: r2dbc:postgresql://username:password@localhost:5433/db_movements
    username: username
    password: password
  datasource:
    url: jdbc:postgresql://localhost:5433/db_movements
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
custom:
  service-url: ${CUSTOMER_SERVICE_URL:http://localhost:8081/api/v1/customers}
server:
  port: 8082
